#version 460

// -----------------------------------------------------------------------------

#include "../interop.h"

// -----------------------------------------------------------------------------
// Topology

layout(buffer_reference, scalar)
buffer Vertices {
  Vertex v[];
};

layout(buffer_reference, scalar)
buffer Indices {
  uint u32[];
};

layout(buffer_reference, scalar)
buffer InstanceDataBufferRef {
  RTInstanceData instances[];
};

#include <shared/rt_unpack_geometry.glsl>

// -----------------------------------------------------------------------------

hitAttributeEXT vec2 hitAttribs;

layout(location = 0) rayPayloadInEXT HitPayload_t payload;

layout(scalar, set = kDescriptorSet_Internal, binding = kDescriptorSetBinding_Sample11_MaterialSBO)
buffer RayTracingMaterialSBO_ {
  RayTracingMaterial materials[];
};

layout(set = kDescriptorSet_Scene, binding = kDescriptorSet_Scene_Textures)
uniform sampler2D uTextureChannels[];

layout(push_constant, scalar)
uniform PushConstant_ {
  PushConstant pushConstant;
};

// -----------------------------------------------------------------------------

void main() {
  // ----------------------------
  // TOPOLOGY.

  const uint primitive_id = gl_PrimitiveID;
  const uint material_id  = gl_InstanceCustomIndexEXT;
  const uint kInvalidIndexU24 = 0x00FFFFFF;

  RTInstanceData instance = GetInstanceData();
  Triangle_t tri = unpack_triangle(instance.vertexAddr, instance.indexAddr, primitive_id);
  vec2 uv = calculate_texcoord(tri, barycenter_from_hit(hitAttribs));

  // ----------------------------
  // SHADING.

  float opacity = 1.0f;

  if (material_id != kInvalidIndexU24)
  {
    RayTracingMaterial mat = materials[nonuniformEXT(material_id)];

    vec4 color = texture(GetTexture(mat.diffuse_texture_id), uv)
               * mat.diffuse_factor
               ;
    opacity = (color.a > mat.alpha_cutoff) ? 1.0f : 0.0f;
  }

  if (opacity < 0.99f) {
    ignoreIntersectionEXT;
  }
}

// -----------------------------------------------------------------------------
