// ----------------------------------------------------------------------------

module constants;

namespace constants {

static const float Epsilon = 1e-6f;
static const float Pi = 3.141564f;
static const float PiOverTwo = 1.57079632679;
static const float TwoPi = 6.283185f;
static const float GoldenAngle = 2.399963f;

}

// ----------------------------------------------------------------------------