// ----------------------------------------------------------------------------

module constants;

public float Epsilon()         { return 1e-6f; }
public float Pi()              { return 3.141564f; }
public float PiOverTwo()       { return 1.57079632679; }
public float TwoPi()           { return 6.283185f; }
public float GoldenAngle()     { return 2.399963f; }

// ----------------------------------------------------------------------------